var a = 20;
var b = 10;
console.log(a+b)
console.log(a-b)
console.log(a*b)
console.log(a%b)
console.log(a/b)
console.log(a+=b)
console.log(a-=b)
console.log(a*=b)
console.log(a%=b)
console.log(a/b)
console.log(a>b && a<b)
console.log(a <= b && a >= b)
console.log(a != b && a == b)
console.log(b != a && b == a)
console.log(b < a && b > a)
console.log(a > b || a < b)
console.log(a <= b || a >= b)
console.log(a != b || a == b)
console.log(b != a || b == a)
console.log(b < a || b > a)
console.log(a > b != a < b)
console.log(a <= b != a >= b)
console.log(a != b != a == b)
console.log(b != a != b == a)
console.log(b < a != b > a)
console.log(a)
console.log(a++)
console.log(--a)
console.log(a)
console.log(b)
console.log(b++)
console.log(--b)
console.log(b)
console.log(++a + ++b)
console.log(++a - ++b)
console.log(++a * ++b)
console.log(++a % ++b)
console.log(++a / ++b)
console.log(a++ + b++)
console.log(a++ - b++)
console.log(a++ * b++)
console.log(a++ % b++)
console.log(a++/ b++)